### ISSUE TITLE
Show bottom right icon optionally

### ISSUE THREAD

**Issue by horczech** [coinzdude/javascript-errors-notifier#24]
The icon at the bottom right is annoying. It would be very nice if you would add an option to hide it and keep only the extension icon in the navigation bar 

![image](https://github.com/coinzdude/javascript-errors-notifier/assets/5252663/42300e37-3b5c-4d1b-b301-bee0494a8da2)

**Comment by coinzdude** [comment]
Great suggestion

**Comment by coinzdude** [comment]
@horczech just added this to v16 of the extension, and I'm awaiting publishing to the store now. I found I had to set the feature as the inverted label of "Hide icon in page" due to the nature of the default data store for the options. Basically new non-existent options don't flag specifically as "false", and instead they are just non-existent when false, so I have to only track "true" when set explicitly. I don't know if that was intended when this extension was created, but I ran with the model I inherited for the time being. Maybe one day I can rewrite it to explicitly store 'false', but I think it works well. Just let me know!
